Upgrade prisma to v6
I ran into issues that I couldn't resolve with the previous version on
Vercel. Upgrading should hopefully help. This is the error:

PrismaClientInitializationError: Unknown PRISMA_QUERY_ENGINE_LIBRARY rhel-openssl-3.2.x. Possible binaryTargets: darwin, darwin-arm64, debian-openssl-1.0.x, debian-openssl-1.1.x, debian-openssl-3.0.x, rhel-openssl-1.0.x, rhel-openssl-1.1.x, rhel-openssl-3.0.x, linux-arm64-openssl-1.1.x, linux-arm64-openssl-1.0.x, linux-arm64-openssl-3.0.x, linux-arm-openssl-1.1.x, linux-arm-openssl-1.0.x, linux-arm-openssl-3.0.x, linux-musl, linux-nixos, windows, freebsd11, freebsd12, freebsd13, openbsd, netbsd, arm, native or a path to the query engine library.
You may have to run prisma generate for your changes to take effect.
    at RequestHandler.request (/var/task/node_modules/@prisma/client/runtime/index.js:49028:15)
    at async PrismaClient._request (/var/task/node_modules/@prisma/client/runtime/index.js:49919:18)
    at async getServerSideProps (/var/task/.next/server/pages/index.js:307:26)
    at async Object.renderToHTML (/var/task/node_modules/next/dist/server/render.js:508:20)
    at async doRender (/var/task/node_modules/next/dist/server/base-server.js:687:38)
    at async cacheEntry.responseCache.get.isManualRevalidate.isManualRevalidate (/var/task/node_modules/next/dist/server/base-server.js:796:28)
    at async /var/task/node_modules/next/dist/server/response-cache/index.js:80:36 {
  clientVersion: '3.15.2',
  errorCode: undefined,
  page: '/'
}